import { createHash } from "node:crypto";
import { config } from "./config";
import { ApiResponseError } from "./api-client";

// ── rail0_id checksum verification ────────────────────────────────────────────

/**
 * Returns true if `paymentId` was generated by rail0-api.
 *
 * Layout of a valid API payment ID (32 bytes, hex-encoded after "0x"):
 *   bytes  0.. 3  — last 4 bytes of SHA-256(payload)   ← checksum
 *   bytes  4..31  — 28 random bytes                    ← payload
 *
 * Any `paymentId` not matching this pattern was created directly on-chain
 * (the RAIL0 contract is public) and should be ignored by Ponder.
 */
export function isApiPaymentId(paymentId: `0x${string}`): boolean {
  const bytes = Buffer.from(paymentId.slice(2), "hex");
  if (bytes.length !== 32) return false;
  const checksum = bytes.subarray(0, 4);
  const payload  = bytes.subarray(4);
  const digest   = createHash("sha256").update(payload).digest();
  return digest.subarray(28).equals(checksum);
}

// ── API update helpers ────────────────────────────────────────────────────────

/**
 * Retries an async function up to maxAttempts times with exponential backoff.
 *
 * On the first successful call returns { ok: true }.
 * After exhausting all attempts returns { ok: false, error } with the last
 * error message, without throwing — callers decide how to handle the failure.
 */
export async function withRetry(
  fn: () => Promise<unknown>,
  maxAttempts = config.apiMaxAttempts,
  baseDelayMs = config.apiBaseDelayMs,
): Promise<{ ok: true; attempts: number } | { ok: false; error: string }> {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      await fn();
      if (attempt > 1) {
        console.log(JSON.stringify({ component: "indexer", event: "notify_api_recovered", attempt }));
      }
      return { ok: true, attempts: attempt };
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      if (err instanceof ApiResponseError) {
        console.log(JSON.stringify({ component: "indexer", event: "notify_api_error_response", attempt, status: err.status, error }));
        return { ok: false, error };
      }
      if (attempt < maxAttempts) {
        console.log(JSON.stringify({ component: "indexer", event: "notify_api_retry", attempt, error }));
        await new Promise((r) => setTimeout(r, baseDelayMs * 2 ** (attempt - 1)));
      } else {
        return { ok: false, error };
      }
    }
  }
  return { ok: false, error: "Unknown error" };
}
